# This is a basic workflow

name: CI

# Controls when the workflow will run
on: 
  # Teriggers the workflow on push or pull request event but only for the main branch
  push:
    branches: [ main ] #other setting [ main,dev ]
  pull_request:
    branches: [ main ]
   
   # Allows you to run workflow manually from the actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs:
  # This workflow contains a single job called "build"
  build:  # build-and-release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # Or windows-latest Or macos 
    
    # Steps reperesent a sequence of tasks that will be excuted as part of the job
    steps: 
     # Check out your repository under $GITHUB_WORKSPACE, so your job will access it
     - uses: action/checkout@v3
     
     # Runs a single command using the runners shell
     - name: Run a one line scrip
       run: echo Hello Javad Bayat
       
     # Runs a set of commands using the runners shell
     - name: Run multi-line script
       run: |
         echo add other actions to build,
         echo test, and deploy your project
    
    
    
    
    
    
    
 
